AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - script/**/*
    - spec/**/*
    - untracked/**/*
    - vendor/**/*
    - tmp/**/*

Metrics/AbcSize:
  Max: 24

Metrics/LineLength:
  Max: 178

Metrics/MethodLength:
  Max: 11

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/EmptyLines:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingComma:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/UnneededPercentQ:
  Enabled: false
